### PR TITLE
Fix start_row/end_row logic

### LINKED ISSUE #30: Some permutations of width, height, and chunk size fail
There seems to be a subtle error in how the starting and ending rows are calculated for `pixel_accumulator`. It's related to the byte length of one row exceeding the chunk size, but it's more subtle than that.

Minimal reproducible example:
```rust
fn main() {
    let result = generate_image((256 * 1024 / 4) + 256, 256);
    println!("{result:?}");
}

fn generate_image(width: u32, height: u32) -> Result<(), Box<dyn std::error::Error>> {
    let data = vec![0u8; 4 * width as usize * height as usize];
    
    let file_name = format!("{width}x{height}.png");
    let file = std::fs::OpenOptions::new()
        .create(true)
        .write(true)
        .truncate(true)
        .open(file_name)?;
    let writer = std::io::BufWriter::new(file);
    
    let mut header = mtpng::Header::new();
    header.set_size(width, height)?;
    
    let options = mtpng::encoder::Options::new();

    let mut encoder = mtpng::encoder::Encoder::new(writer, &options);
    encoder.write_header(&header)?;
    encoder.write_image_rows(&data)?;
    encoder.finish()?;
    
    Ok(())
}
```
Output:
```
Err(Custom { kind: Other, error: "Incomplete image input" })
```
Here, I've made the rows 1024 bytes longer than the default chunk size of 256 KiB; however, that's not always enough to trigger the bug. For example, using a height less than 256 in the above example will not fail, and if you add 128 to the width instead of 256, it will not fail unless the height is at least 512.

What happens in these cases is `start_row(0)` and `end_row(0)` both return 0. Then, once `pixel_accumulator` copies the first row, `pixel_accumulator.is_full()` will never return `true`, so the encoder just iterates over all the rows doing nothing. When `encoder.finish()` is called, `chunks_output` is stuck at 0.

### PR DESCRIPTION
**Pull request by spindlymist**
Fixes #30.

I was able to fix the issue by rounding the chunk size to a multiple of the stride and reframing the arithmetic around the number of rows per chunk.

I ran this on the samples and pngsuite and compared the results with the latest version. Of the 40 test cases, 24 were binary identical, 16 had binary differences, and 0 had differences in pixel data. The total size of all the samples was about 1.5 KiB less after the change. I did not compare speed.

### CODE REVIEW

File: src/encoder.rs [hunk 1]
```diff
@@ -813,16 +816,13 @@ impl<'a, W: Write> Encoder<'a, W> {
         }
 
         self.header = *header;
-
-        let stride = self.header.stride() + 1;
+        
+        let chunk_size = self.options.chunk_size;
+        let stride = self.header.stride();
```
Comment (bvibber) [inline src/encoder.rs]: This seems wrong to me; the added byte for the stride is for the filter type byte at the beginning of every row. Removing that will put the size calculations for the chunks off.

**Comment by bvibber** [comment]
Haven't tested this yet, but aside from the stride calculation being off this looks mostly correct. :)

File: src/encoder.rs (hunk 1 above)
Comment (spindlymist) [reply src/encoder.rs]: I think for the purpose of determining the number of chunks, we are concerned with the stride of the input data, which doesn't have filter bytes. The `FilterChunk` constructor adds one byte to its buffer for the filter type (https://github.com/bvibber/mtpng/blob/main/src/encoder.rs#L265). I could definitely be wrong though!

Comment (bvibber) [reply src/encoder.rs]: What you're concerned with in the chunk size is the input data *to the compression phase*, which does include the filter type byte on each row. :)

Comment (spindlymist) [reply src/encoder.rs]: I see, I had interpreted `chunk_size` as the number of bytes from the input data that would be processed per thread, but the chunk size for compression makes sense. I think the +1 can be added without having to change anything else.

**Comment by spindlymist** [comment]
I added the +1 back in and tested it out. The results look good. No size difference, but there are still some binary differences. Sorry for the ugly commit history; hopefully it can be squashed.

One question that remains is how to round `rows_per_chunk`. I rounded up because it cleanly ensures it will never be 0, but it might be better to do a proper round and give it a minimum of 1 explicitly.

**Comment by bvibber** [comment]
No worries on the commit history, I have a lot of weird works in progress that never got squashed out. ;) The mess is part of the charm around here.

I'll take a more thorough look at it on the test files, just to confirm what the remaining binary differences are.

First thing's first looking at the original bug:

Looking at the 256k + 1024 bytes example:
* 256k + 1024 + 1 is filtered stride of 262144 + 1024 + 1 = 263169
* original chunks_total calculation was 263169 stride * 256 height = 67371264 / 262144 chunk_size = rounds down to 257 with a small remainder
* start_row(0) is 0 index * 256 height / 257 chunks_total = 0
* end_row(0) is 1 index * 256 height / 257 chunks_total = 0.996 rounds down to 0 :D

So the problem as we can see is from ending up with a chunk size whose average height is less than one row :D

I think rounding up `rows_per_chunk` is fine here -- we previously were averaging around the target chunk size and just sort of hoping we actually ended up at the right end row (whoops) -- it's conceptually simpler to say "chunk size is interpreted as minimum chunk size" and let the final chunk potentially be a short one, with the explicit check for the final row. :)

Having looked at that -- some binary differences are to be expected as the chunks may differ what in rows their boundaries are at due to the different rounding. This should be fine then. :D

Will take a quick peek and if it runs fine I'll merge
